steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
  - gcloud
  - functions
  - deploy
  - cf_cloud_build
  - --region=us-central1
  - --allow-unauthenticated
  - --source=https://github.com/ctcruz/ac_cloud_function/tree/main/cf_cloud_build
  - --trigger-http
  - --runtime=python39
  - --memory=128MB
  - --project=cloud-course-432708
  - --entry-point=hello_world
  - --update-labels=course=cloud_functions,env=dev,layer=raw